eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    redis:
      host: localhost
      port: 6379

#  application:
#    name: feeds
#  cloud:
#    config:
#      enabled: false
#    openfeign:
#      circuitbreaker:
#        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10000

server:
  port: 8085
